"""
Base LLM provider protocol and shared types.

This module defines the abstract interface that every LLM provider must
implement, along with the data classes used to configure requests and
represent responses.

Architecture:
    ``LLMProvider`` is defined as a ``Protocol`` (PEP 544), enabling
    *structural* subtyping -- a class only needs to implement the
    required methods/properties; explicit inheritance is optional.

    ``BaseLLMProvider`` is a convenience ABC that provides shared
    plumbing (cost calculation, token estimation, default config).
    Concrete providers (e.g. ``AnthropicProvider``) should inherit
    from it.

Exception hierarchy::

    ProviderError
    ├── RateLimitError       (retry_after hint)
    ├── AuthenticationError  (invalid / missing API key)
    └── TokenLimitError      (prompt exceeds context window)

Maintenance:
    To add a new provider, subclass ``BaseLLMProvider`` and implement
    all abstract methods.  Register the provider in
    ``chess_llm.providers.registry``.

Security:
    The ``BaseLLMProvider.__repr__`` masks the stored API key so that
    accidental ``print()`` or logging calls never expose secrets.
"""

import asyncio
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Protocol, runtime_checkable


# ---------------------------------------------------------------------------
# Exception hierarchy
# ---------------------------------------------------------------------------


class ProviderError(Exception):
    """Base exception for all provider-related errors.

    Attributes:
        provider: Identifier of the provider that raised the error.
        details:  Optional dict with extra diagnostic information.
    """

    def __init__(
        self,
        message: str,
        provider: str = "",
        details: Optional[Dict[str, Any]] = None,
    ):
        super().__init__(message)
        self.provider = provider
        self.details = details or {}


class RateLimitError(ProviderError):
    """The provider's rate limit has been exceeded.

    Attributes:
        retry_after: Suggested delay (in seconds) before retrying, if the
                     provider supplied one.
    """

    def __init__(
        self,
        message: str,
        provider: str = "",
        retry_after: Optional[float] = None,
        details: Optional[Dict[str, Any]] = None,
    ):
        super().__init__(message, provider, details)
        self.retry_after = retry_after


class AuthenticationError(ProviderError):
    """API authentication failed (invalid or missing key)."""

    pass


class TokenLimitError(ProviderError):
    """The request exceeds the model's token limit.

    Attributes:
        requested_tokens: How many tokens the request needed.
        max_tokens:       The model's maximum context size.
    """

    def __init__(
        self,
        message: str,
        provider: str = "",
        requested_tokens: int = 0,
        max_tokens: int = 0,
        details: Optional[Dict[str, Any]] = None,
    ):
        super().__init__(message, provider, details)
        self.requested_tokens = requested_tokens
        self.max_tokens = max_tokens


# ---------------------------------------------------------------------------
# Request configuration
# ---------------------------------------------------------------------------


@dataclass
class LLMConfig:
    """
    Per-request configuration for an LLM call.

    Attributes:
        max_tokens:      Maximum number of tokens to generate.
        temperature:     Sampling temperature (0.0 = deterministic).
        top_p:           Nucleus sampling threshold.
        stop_sequences:  Stop strings that terminate generation.
        system_prompt:   Optional system-level instruction.
        extra:           Provider-specific key-value pairs forwarded
                         directly to the underlying API.
    """

    max_tokens: int = 1024
    temperature: float = 0.7
    top_p: Optional[float] = None
    stop_sequences: List[str] = field(default_factory=list)
    system_prompt: Optional[str] = None

    extra: Dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Response types
# ---------------------------------------------------------------------------


@dataclass
class UsageStats:
    """
    Token usage and cost breakdown for a single LLM response.

    Attributes:
        input_tokens:  Tokens consumed by the prompt.
        output_tokens: Tokens generated by the model.
        total_tokens:  Sum of input + output.
        input_cost:    USD cost of input tokens.
        output_cost:   USD cost of output tokens.
        total_cost:    Combined USD cost.
    """

    input_tokens: int = 0
    output_tokens: int = 0
    total_tokens: int = 0

    input_cost: float = 0.0
    output_cost: float = 0.0
    total_cost: float = 0.0

    @property
    def cost_formatted(self) -> str:
        """Return the total cost as a human-readable USD string."""
        return f"${self.total_cost:.6f}"


@dataclass
class LLMResponse:
    """
    Standardised response from any LLM provider.

    The ``content`` field holds the generated text.  Usage statistics,
    latency, and provider metadata are attached for tracking and debugging.

    Attributes:
        content:       Generated text.
        model:         Model ID that produced the response.
        provider:      Provider identifier.
        usage:         Token counts and costs.
        finish_reason: Why generation stopped (e.g. ``"stop"``, ``"length"``).
        created_at:    Timestamp of creation.
        latency_ms:    Wall-clock time for the API call (milliseconds).
        raw_response:  Optional provider-specific metadata (never contains
                       secrets -- only IDs, types, and stop reasons).
    """

    content: str
    model: str
    provider: str

    usage: UsageStats = field(default_factory=UsageStats)

    finish_reason: str = "stop"
    created_at: datetime = field(default_factory=datetime.utcnow)
    latency_ms: float = 0.0

    raw_response: Optional[Dict[str, Any]] = None

    def __str__(self) -> str:
        return self.content


# ---------------------------------------------------------------------------
# Provider protocol (structural subtyping)
# ---------------------------------------------------------------------------


@runtime_checkable
class LLMProvider(Protocol):
    """
    Protocol that every LLM provider must satisfy.

    Uses ``@runtime_checkable`` so callers can verify compliance with
    ``isinstance(obj, LLMProvider)``.  Concrete classes do *not* need to
    inherit from this protocol -- they just need matching signatures.
    """

    @property
    def provider_id(self) -> str:
        """Unique identifier (e.g. ``"anthropic"``, ``"openai"``)."""
        ...

    @property
    def model_id(self) -> str:
        """Current model identifier (e.g. ``"claude-sonnet-4-20250514"``)."""
        ...

    @property
    def display_name(self) -> str:
        """Human-readable name for display (e.g. ``"Claude Sonnet 4"``)."""
        ...

    @property
    def supports_vision(self) -> bool:
        """Whether this provider/model supports image inputs."""
        ...

    @property
    def max_context_tokens(self) -> int:
        """Maximum context window size in tokens."""
        ...

    @property
    def max_output_tokens(self) -> int:
        """Maximum output tokens the model can generate."""
        ...

    def complete(
        self,
        prompt: str,
        config: Optional[LLMConfig] = None,
    ) -> LLMResponse:
        """
        Generate a text completion.

        Args:
            prompt: The user prompt/message.
            config: Optional per-request configuration.

        Returns:
            An ``LLMResponse`` with generated content and metadata.

        Raises:
            ProviderError:        General provider failure.
            RateLimitError:       Rate limit exceeded.
            AuthenticationError:  Invalid API key.
            TokenLimitError:      Prompt exceeds context window.
        """
        ...

    def complete_messages(
        self,
        messages: List[Dict[str, Any]],
        config: Optional[LLMConfig] = None,
    ) -> LLMResponse:
        """
        Generate a completion from a messages list.

        Args:
            messages: List of message dicts with ``role`` and ``content`` keys.
            config:   Optional per-request configuration.

        Returns:
            An ``LLMResponse`` with generated content and metadata.
        """
        ...

    def complete_with_images(
        self,
        prompt: str,
        images: List[bytes],
        config: Optional[LLMConfig] = None,
    ) -> LLMResponse:
        """
        Generate a completion that includes image context.

        Args:
            prompt: The user prompt/message.
            images: List of images as raw bytes (PNG / JPEG).
            config: Optional per-request configuration.

        Raises:
            NotImplementedError: If the model lacks vision support.
        """
        ...

    def estimate_tokens(self, text: str) -> int:
        """
        Approximate the number of tokens in *text*.

        This is a fast heuristic -- actual tokenisation may differ.
        """
        ...

    def get_cost_per_token(self) -> tuple[float, float]:
        """
        Return ``(input_cost_per_million, output_cost_per_million)`` in USD.
        """
        ...

    async def acomplete(
        self,
        prompt: str,
        config: Optional[LLMConfig] = None,
    ) -> LLMResponse:
        """
        Async version of ``complete()``.
        """
        ...

    async def acomplete_messages(
        self,
        messages: List[Dict[str, Any]],
        config: Optional[LLMConfig] = None,
    ) -> LLMResponse:
        """
        Async version of ``complete_messages()``.
        """
        ...


# ---------------------------------------------------------------------------
# Abstract base class with shared plumbing
# ---------------------------------------------------------------------------


class BaseLLMProvider(ABC):
    """
    Convenience base class for LLM provider implementations.

    Provides default implementations for token estimation, cost
    calculation, and image rejection.  Concrete subclasses must
    implement all ``@abstractmethod`` members.

    Security:
        ``__repr__`` masks the API key to prevent accidental exposure.
    """

    def __init__(
        self,
        model_id: str,
        api_key: Optional[str] = None,
        **kwargs: Any,
    ):
        """
        Args:
            model_id: The model identifier to use for API calls.
            api_key:  API key (falls back to environment if ``None``).
            **kwargs: Provider-specific options.
        """
        self._model_id = model_id
        self._api_key = api_key
        self._options = kwargs

    def __repr__(self) -> str:
        """Safe repr that never exposes the API key."""
        masked = "****" if self._api_key else "None"
        return (
            f"{type(self).__name__}(model_id={self._model_id!r}, "
            f"api_key={masked!r})"
        )

    # -- Abstract properties ------------------------------------------------

    @property
    @abstractmethod
    def provider_id(self) -> str:
        """Unique identifier for this provider."""
        ...

    @property
    def model_id(self) -> str:
        """Current model identifier."""
        return self._model_id

    @property
    @abstractmethod
    def display_name(self) -> str:
        """Human-readable name."""
        ...

    @property
    @abstractmethod
    def supports_vision(self) -> bool:
        """Whether this model supports images."""
        ...

    @property
    @abstractmethod
    def max_context_tokens(self) -> int:
        """Maximum context window."""
        ...

    @property
    @abstractmethod
    def max_output_tokens(self) -> int:
        """Maximum output tokens."""
        ...

    # -- Abstract methods ---------------------------------------------------

    @abstractmethod
    def complete(
        self,
        prompt: str,
        config: Optional[LLMConfig] = None,
    ) -> LLMResponse:
        """Generate a text completion."""
        ...

    @abstractmethod
    def get_cost_per_token(self) -> tuple[float, float]:
        """Return ``(input_cost/M, output_cost/M)`` in USD."""
        ...

    # -- Default implementations --------------------------------------------

    def complete_messages(
        self,
        messages: List[Dict[str, Any]],
        config: Optional[LLMConfig] = None,
    ) -> LLMResponse:
        """
        Generate a completion from a messages list.

        Default implementation extracts the last user message and delegates
        to ``complete()``.  Override in subclasses for native multi-turn
        support.

        Args:
            messages: List of message dicts with ``role`` and ``content``.
            config:   Per-request configuration.
        """
        # Extract the last user message as the prompt
        prompt = ""
        for msg in reversed(messages):
            if msg.get("role") == "user":
                prompt = msg.get("content", "")
                break
        if not prompt and messages:
            prompt = messages[-1].get("content", "")
        return self.complete(prompt, config)

    def complete_with_images(
        self,
        prompt: str,
        images: List[bytes],
        config: Optional[LLMConfig] = None,
    ) -> LLMResponse:
        """Generate a completion with images (override in vision-capable providers)."""
        if not self.supports_vision:
            raise NotImplementedError(
                f"Provider {self.provider_id} model {self.model_id} "
                f"does not support vision"
            )
        raise NotImplementedError("Vision support not implemented")

    def estimate_tokens(self, text: str) -> int:
        """
        Rough token estimate using ~4 characters per token.

        Override for provider-specific tokenisation.
        """
        return len(text) // 4

    # -- Async methods (default: thread-pool delegation) --------------------

    async def acomplete(
        self,
        prompt: str,
        config: Optional[LLMConfig] = None,
    ) -> LLMResponse:
        """
        Async version of ``complete()``.

        Default implementation delegates to the sync ``complete()`` in a
        thread pool.  Override in subclasses that have native async SDK
        support (e.g. ``AsyncAnthropic``, ``AsyncOpenAI``).
        """
        return await asyncio.to_thread(self.complete, prompt, config)

    async def acomplete_messages(
        self,
        messages: List[Dict[str, Any]],
        config: Optional[LLMConfig] = None,
    ) -> LLMResponse:
        """
        Async version of ``complete_messages()``.

        Default implementation delegates to sync ``complete_messages()`` in
        a thread pool.  Override for native async support.
        """
        return await asyncio.to_thread(self.complete_messages, messages, config)

    # -- Cost / config helpers ----------------------------------------------

    def _calculate_cost(self, usage: UsageStats) -> UsageStats:
        """Populate cost fields on *usage* using this model's pricing."""
        input_price, output_price = self.get_cost_per_token()
        usage.input_cost = (usage.input_tokens / 1_000_000) * input_price
        usage.output_cost = (usage.output_tokens / 1_000_000) * output_price
        usage.total_cost = usage.input_cost + usage.output_cost
        return usage

    def _get_default_config(self) -> LLMConfig:
        """Return a fresh default ``LLMConfig``."""
        return LLMConfig()
