"""
Usage and cost tracking for LLM requests.

Every LLM call made through this library can be recorded in a
``UsageTracker``, providing:

    - Per-request token counts and USD costs
    - Aggregations by provider, model, and prompt template
    - Budget limit enforcement
    - Latency and throughput metrics

The module exposes a **global singleton** tracker (``get_tracker()``) for
convenience, but you can also create standalone instances.

Usage::

    from chess_llm.tracking import get_tracker

    tracker = get_tracker()

    # After making LLM requests...
    print(f"Total cost: ${tracker.total_cost:.4f}")
    print(f"Total tokens: {tracker.total_tokens}")
    print(tracker.get_summary())

Thread safety:
    The tracker uses basic ``list.append()`` which is atomic in CPython,
    but for high-concurrency applications consider a dedicated metrics
    backend.

Maintenance:
    If new dimensions are needed (e.g. tracking by user or session), add
    an optional field to ``UsageRecord`` and a corresponding
    ``get_cost_by_*`` method to ``UsageTracker``.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# Single-request record
# ---------------------------------------------------------------------------


@dataclass
class UsageRecord:
    """
    Immutable record of a single LLM request.

    Attributes:
        timestamp:     When the request was made.
        provider:      Provider identifier (e.g. ``"anthropic"``).
        model:         Model ID.
        prompt_id:     Prompt template ID (``None`` for ad-hoc prompts).
        input_tokens:  Tokens consumed by the prompt.
        output_tokens: Tokens generated by the model.
        total_tokens:  Sum of input + output.
        cost_usd:      Actual USD cost of the request.
        latency_ms:    Wall-clock time in milliseconds.
        success:       Whether the request completed without error.
        error:         Error message if ``success`` is ``False``.
    """

    timestamp: datetime
    provider: str
    model: str
    prompt_id: Optional[str]
    input_tokens: int
    output_tokens: int
    total_tokens: int
    cost_usd: float
    latency_ms: float
    success: bool
    error: Optional[str] = None

    @property
    def tokens_per_second(self) -> float:
        """Output tokens generated per second (0.0 if latency is zero)."""
        if self.latency_ms <= 0:
            return 0.0
        return self.output_tokens / (self.latency_ms / 1000)


# ---------------------------------------------------------------------------
# Tracker (aggregator)
# ---------------------------------------------------------------------------


@dataclass
class UsageTracker:
    """
    Accumulates ``UsageRecord`` entries and provides aggregate metrics.

    Optionally enforces a USD budget limit -- when exceeded,
    ``is_over_budget`` returns ``True`` so callers can decide whether
    to continue.

    Attributes:
        records:          All recorded requests.
        budget_limit_usd: Optional spending cap in USD.
    """

    records: List[UsageRecord] = field(default_factory=list)
    budget_limit_usd: Optional[float] = None

    # -----------------------------------------------------------------------
    # Recording
    # -----------------------------------------------------------------------

    def record(
        self,
        provider: str,
        model: str,
        input_tokens: int,
        output_tokens: int,
        cost_usd: float,
        latency_ms: float,
        prompt_id: Optional[str] = None,
        success: bool = True,
        error: Optional[str] = None,
    ) -> UsageRecord:
        """
        Record a single LLM request.

        Args:
            provider:      Provider name (e.g. ``"anthropic"``).
            model:         Model identifier.
            input_tokens:  Prompt token count.
            output_tokens: Generated token count.
            cost_usd:      Request cost in USD.
            latency_ms:    Request latency in milliseconds.
            prompt_id:     Optional prompt template identifier.
            success:       Whether the request succeeded.
            error:         Error description (if ``success`` is ``False``).

        Returns:
            The created ``UsageRecord``.
        """
        entry = UsageRecord(
            timestamp=datetime.now(),
            provider=provider,
            model=model,
            prompt_id=prompt_id,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            total_tokens=input_tokens + output_tokens,
            cost_usd=cost_usd,
            latency_ms=latency_ms,
            success=success,
            error=error,
        )
        self.records.append(entry)
        return entry

    # -----------------------------------------------------------------------
    # Aggregate properties
    # -----------------------------------------------------------------------

    @property
    def total_cost(self) -> float:
        """Total USD cost across all recorded requests."""
        return sum(r.cost_usd for r in self.records)

    @property
    def total_tokens(self) -> int:
        """Total tokens (input + output) across all requests."""
        return sum(r.total_tokens for r in self.records)

    @property
    def total_requests(self) -> int:
        """Number of recorded requests."""
        return len(self.records)

    @property
    def successful_requests(self) -> int:
        """Number of requests that completed successfully."""
        return sum(1 for r in self.records if r.success)

    @property
    def failed_requests(self) -> int:
        """Number of requests that failed."""
        return sum(1 for r in self.records if not r.success)

    @property
    def average_latency_ms(self) -> float:
        """Mean latency across all requests (0.0 if none recorded)."""
        if not self.records:
            return 0.0
        return sum(r.latency_ms for r in self.records) / len(self.records)

    # -----------------------------------------------------------------------
    # Budget management
    # -----------------------------------------------------------------------

    @property
    def budget_remaining(self) -> Optional[float]:
        """Remaining budget in USD, or ``None`` if no limit is set."""
        if self.budget_limit_usd is None:
            return None
        return max(0.0, self.budget_limit_usd - self.total_cost)

    @property
    def is_over_budget(self) -> bool:
        """``True`` if spending has reached or exceeded the budget limit."""
        if self.budget_limit_usd is None:
            return False
        return self.total_cost >= self.budget_limit_usd

    # -----------------------------------------------------------------------
    # Grouped cost breakdowns
    # -----------------------------------------------------------------------

    def get_cost_by_provider(self) -> Dict[str, float]:
        """Return total cost grouped by provider name."""
        costs: Dict[str, float] = {}
        for record in self.records:
            costs[record.provider] = costs.get(record.provider, 0.0) + record.cost_usd
        return costs

    def get_cost_by_model(self) -> Dict[str, float]:
        """Return total cost grouped by model ID."""
        costs: Dict[str, float] = {}
        for record in self.records:
            costs[record.model] = costs.get(record.model, 0.0) + record.cost_usd
        return costs

    def get_cost_by_prompt(self) -> Dict[str, float]:
        """Return total cost grouped by prompt template ID."""
        costs: Dict[str, float] = {}
        for record in self.records:
            key = record.prompt_id or "unknown"
            costs[key] = costs.get(key, 0.0) + record.cost_usd
        return costs

    # -----------------------------------------------------------------------
    # Summary
    # -----------------------------------------------------------------------

    def get_summary(self) -> Dict[str, Any]:
        """
        Return a comprehensive summary dict suitable for logging or
        serialisation.
        """
        return {
            "total_requests": self.total_requests,
            "successful_requests": self.successful_requests,
            "failed_requests": self.failed_requests,
            "total_tokens": self.total_tokens,
            "total_cost_usd": round(self.total_cost, 6),
            "average_latency_ms": round(self.average_latency_ms, 2),
            "cost_by_provider": self.get_cost_by_provider(),
            "cost_by_model": self.get_cost_by_model(),
            "cost_by_prompt": self.get_cost_by_prompt(),
            "budget_limit_usd": self.budget_limit_usd,
            "budget_remaining_usd": self.budget_remaining,
            "is_over_budget": self.is_over_budget,
        }

    def clear(self) -> None:
        """Discard all recorded data."""
        self.records.clear()


# ---------------------------------------------------------------------------
# Global singleton
# ---------------------------------------------------------------------------

_global_tracker: Optional[UsageTracker] = None


def get_tracker() -> UsageTracker:
    """
    Return the global ``UsageTracker`` singleton.

    Creates a new instance on first call.  Use ``reset_tracker()`` to
    discard accumulated data and start fresh.
    """
    global _global_tracker
    if _global_tracker is None:
        _global_tracker = UsageTracker()
    return _global_tracker


def reset_tracker() -> None:
    """Replace the global tracker with a fresh empty instance."""
    global _global_tracker
    _global_tracker = UsageTracker()
